execute pathogen#infect()

syntax enable
set background=dark
colorscheme default
" Workaround a problem with solarized and vim-gitgutter.
" https://github.com/airblade/vim-gitgutter/issues/696
highlight! link SignColumn LineNr
autocmd ColorScheme * highlight! link SignColumn LineNr

set tabstop=8 expandtab shiftwidth=4 softtabstop=4
set number
set relativenumber
set ruler
set wildmenu
set backspace=indent,eol,start
set autoindent
set smartindent
set smarttab
set history=200
set nocompatible

" Switch buffers without saving
set hidden

" Better search
set hlsearch
set incsearch

" Keep swap files in a single location
set backupdir=~/.vim/sessions
set dir=~/.vim/sessions

" FZF integration
set rtp+=~/.fzf

" For faster refresh of gitgutter
set updatetime=100
set signcolumn=yes

" Remember cursor position
au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g`\"" | endif

" Save current view settings on a per-window, per-buffer basis.
function! AutoSaveWinView()
    if !exists("w:SavedBufView")
        let w:SavedBufView = {}
    endif
    let w:SavedBufView[bufnr("%")] = winsaveview()
endfunction

" Restore current view settings.
function! AutoRestoreWinView()
    let buf = bufnr("%")
    if exists("w:SavedBufView") && has_key(w:SavedBufView, buf)
        let v = winsaveview()
        let atStartOfFile = v.lnum == 1 && v.col == 0
        if atStartOfFile && !&diff
            call winrestview(w:SavedBufView[buf])
        endif
        unlet w:SavedBufView[buf]
    endif
endfunction

" When switching buffers, preserve window view.
if v:version >= 700
    autocmd BufLeave * call AutoSaveWinView()
    autocmd BufEnter * call AutoRestoreWinView()
endif

" File type settings
filetype plugin on
autocmd FileType python setlocal textwidth=100 tabstop=8 expandtab shiftwidth=4 softtabstop=4 cinwords=if,elif,else,for,while,try,except,finally,def,class,with
autocmd FileType javascript,typescript,typescriptreact setlocal shiftwidth=2 softtabstop=2 expandtab softtabstop=2
autocmd FileType xml,html,htmldjango,css,scss setlocal shiftwidth=2 softtabstop=2 expandtab softtabstop=2
autocmd FileType coffee setlocal textwidth=100 tabstop=8 expandtab shiftwidth=2 softtabstop=2

" Custom mappings

" Arrow keys move visible lines
inoremap <Down> <C-R>=pumvisible() ? "\<lt>Down>" : "\<lt>C-O>gj"<CR>
inoremap <Up> <C-R>=pumvisible() ? "\<lt>Up>" : "\<lt>C-O>gk"<CR>

nnoremap Y y$

nmap <Leader>p :FZF<CR>
nmap <Leader>d :Dash<CR>

" Insert current date
nnoremap <F4> "=strftime("%Y-%m-%d")<CR>P
inoremap <F4> <C-R>=strftime("%Y-%m-%d")<CR>
