execute pathogen#infect()

syntax enable
set background=dark
colorscheme default
" Workaround a problem with solarized and vim-gitgutter.
" https://github.com/airblade/vim-gitgutter/issues/696
highlight! link SignColumn LineNr
autocmd ColorScheme * highlight! link SignColumn LineNr

set tabstop=8 expandtab shiftwidth=4 softtabstop=4
set number
set relativenumber
set ruler
set wildmenu
set backspace=indent,eol,start
set autoindent
set smartindent
set smarttab
set history=200
set nocompatible
set nostartofline

" Switch buffers without saving
set hidden

" Better search
set hlsearch
set incsearch

" Keep swap files in a single location
if empty(glob('~/.vim/sessions'))
  silent execute '!mkdir -p ~/.vim/sessions'
endif
set backupdir=~/.vim/sessions
set dir=~/.vim/sessions

" FZF integration
set rtp+=~/.fzf
set rtp+=/opt/homebrew/opt/fzf

" For faster refresh of gitgutter
set updatetime=100
set signcolumn=yes

" File type settings
filetype plugin on
autocmd FileType python setlocal textwidth=100 tabstop=8 expandtab shiftwidth=4 softtabstop=4 cinwords=if,elif,else,for,while,try,except,finally,def,class,with
autocmd FileType javascript,typescript,typescriptreact setlocal shiftwidth=2 softtabstop=2 expandtab softtabstop=2
autocmd FileType xml,html,htmldjango,css,scss setlocal shiftwidth=2 softtabstop=2 expandtab softtabstop=2

" Custom mappings

nnoremap Y y$

nmap <Leader>p :FZF!<CR>
nmap <Leader>f :Rg!<CR>
nmap <Leader>l :Buffers<CR>
nmap <Leader>d :Dash<CR>
nmap <Leader>t :!python3 -m unittest %<CR>
nmap <Leader>r :!python3 %<CR>
nmap <Leader>j :%!python3 -m json.tool<CR>

" Insert current date
nnoremap <F4> "=strftime("%Y-%m-%d")<CR>P
inoremap <F4> <C-R>=strftime("%Y-%m-%d")<CR>


" vim-plug automatic installation (source: https://github.com/junegunn/vim-plug/wiki/tips#automatic-installation)
let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" vim-plug plugins section
call plug#begin('~/.vim/plugged')

Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'junegunn/goyo.vim'

call plug#end()

" Cheatsheet
"
" - `:Goyo`: focused writing
" - `:Flake`: run flake8 in current file and populate quickfix list with the errors
