[ -f ~/.bashrc ] && source ~/.bashrc

set -o vi

export EDITOR=vim
export PS1="\[\e[34m\]\u:\w\\$\[\e[m\] "
export HISTSIZE=10000

alias activate='source .venv/bin/activate'
alias vif='vi $(fzf)'

[ -f ~/.git-completion.bash ] && source ~/.git-completion.bash
[ -f ~/.git-prompt.bash ] && source ~/.git-prompt.sh

# Add ~/bin scripts to $PATH
if [ -d "$HOME/bin" ] ; then
  PATH="$PATH:$HOME/bin"
fi

# Disable Catalina annoying warning about zsh:
export BASH_SILENCE_DEPRECATION_WARNING=1

# export FZF_DEFAULT_COMMAND='fd --type f'

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# Add brew to path
PATH="/opt/homebrew/bin:${PATH}"

export PATH=$HOME/.local/bin:$PATH

# Setting PATH for Python 3.10
# The original version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.10/bin:${PATH}"
export PATH

export LANG=C
