export EDITOR=vim
export HISTSIZE=10000

alias git='LANG=en_US git'
alias dc='docker compose'
# Don't use MacOS ctags. Use hombrew instead
alias ctags='/opt/homebrew/bin/ctags'

[ -f ~/bin/git-completion.bash ] && source ~/bin/git-completion.bash
[ -f ~/bin/git-prompt.sh ] && source ~/bin/git-prompt.sh

PS1='\[\e[34m\]\u:\w$(__git_ps1 " (%s)")\$\[\e[m\] '

# Add ~/bin scripts to $PATH
if [ -d "$HOME/bin" ] ; then
  PATH="$PATH:$HOME/bin"
fi

# Add brew to path
PATH="/opt/homebrew/bin:${PATH}"

export PATH=$HOME/.local/bin:$PATH

# Setting PATH for Python 3.11
# The original version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.11/bin:${PATH}"
export PATH

# Disable Catalina annoying warning about zsh:
export BASH_SILENCE_DEPRECATION_WARNING=1

export FZF_DEFAULT_COMMAND='fd --type f --strip-cwd-prefix'
export FZF_DEFAULT_OPTS='--layout=reverse'

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# Set up Python shell (Manu)
export PYTHONSTARTUP=~/.pythonrc

# In case you want to extend this base .bashrc
[ -f ~/.bashrc_extended ] && source ~/.bashrc_extended
