source ~/.bashrc

set -o vi

export EDITOR=vim
export PYTHONSTARTUP=~/.pythonstartup.py
export PS1="\[\e[32m\]\u\[\e[m\]@\[\e[34m\]\h\[\e[m\]:\[\e[33m\]\w\[\e[m\]$ "
export HISTSIZE=10000

alias activate='source .venv/bin/activate'

source ~/.git-completion.bash

# Setting PATH for Python 3.7
# The original version is saved in .bash_profile.pysave
# PATH="/Library/Frameworks/Python.framework/Versions/3.7/bin:${PATH}:/Users/manu/Library/Python/3.7/bin:/Users/manu/bin:/Users/manu/.npm-packages/bin"
# export PATH

# Setting PATH for Python 3.6
# The original version is saved in .bash_profile.pysave
# PATH="/Library/Frameworks/Python.framework/Versions/3.6/bin:${PATH}"
# export PATH

export FZF_DEFAULT_COMMAND='fd --type f'

# Disable Catalina annoying warning about zsh:
export BASH_SILENCE_DEPRECATION_WARNING=1

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
